name: Docker Tag

on:
  push:
    tags: [ v* ]

jobs:
  build:
    name: Docker Tag
    runs-on: ubuntu-20.04
    steps:
      - name: Print Variables

        shell: bash
        env:
          REPOSITORY_OWNER: ${{ github.repository_owner }}
          REGISTRY_HOSTNAME: ghcr.io
          TAG_NAME: ${{ github.event.ref }}
        run: |
          echo "::group::Parameters"
          echo "REPOSITORY_OWNER : ${REPOSITORY_OWNER}"
          echo "REGISTRY_HOSTNAME: ${REGISTRY_HOSTNAME}"
          echo "TAG_NAME         : ${TAG_NAME}"
          echo "GITHUB_REF       : ${GITHUB_REF}"
          echo "GITHUB_SHA       : ${GITHUB_SHA}"
          echo "::endgroup::"

          echo "::group::event"
          cat ${{ github.event_path }}
          echo "::endgroup::"

          # echo "${{ secrets.GITHUB_TOKEN }}" | docker login https://${REGISTRY_HOSTNAME} -u "${GITHUB_ACTOR}" --password-stdin
          # docker pull ${REGISTRY_HOSTNAME}/${REPOSITORY_OWNER}/azure-ddns:${GITHUB_SHA}
